firstName = input()
secondName = input()
age = int(input())
town = input()
print("You are " + firstName + " " + secondName + ", a " + str(age) + "-years old person from " + town + ".")
#print(f"You are {firstName} {lastName}, a {age}-years old person from {town}.")
